// Development-only DOM regression checks. Install jsdom, or point DEMO_JSDOM at an existing installation.
const { JSDOM, VirtualConsole } = require(process.env.DEMO_JSDOM || "jsdom");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "../dist");
let count = 0;
function check(condition, label) { assert.ok(condition, label); count++; console.log("PASS " + label); }
(async () => {
  const errors = [], connections = [];
  const vc = new VirtualConsole();
  vc.on("jsdomError", (err) => errors.push(err.message));
  let mediaChange;
  const media = { matches: false, addEventListener: (_, listener) => { mediaChange = listener; } };
  const dom = await JSDOM.fromFile(path.join(root, "line/index.html"), {
    resources: "usable", runScripts: "dangerously", pretendToBeVisual: true, virtualConsole: vc,
    beforeParse(w) {
      w.matchMedia = () => media;
      w.fetch = (...args) => { connections.push(args); throw new Error("Unexpected network call"); };
      w.XMLHttpRequest = function () { connections.push("XHR"); throw new Error("Unexpected XHR"); };
    },
  });
  await new Promise((resolve) => dom.window.addEventListener("load", resolve));
  const w = dom.window, d = w.document, $ = (s) => d.querySelector(s);
  const form = $("#line-form"), field = (name) => form.elements.namedItem(name);
  const submit = () => form.dispatchEvent(new w.Event("submit", { bubbles: true, cancelable: true }));
  const set = (name, value) => { field(name).value = value; field(name).dispatchEvent(new w.Event("input", { bubbles: true })); };
  const open = (key) => $(`#rich-menu [data-open=${key}]`).click();
  check(form && d.querySelectorAll("#rich-menu button").length === 6, "初期画面にフォームと6項目のメニュー");
  check(!$("#registration-view").hidden, "PCの初期画面に登録フォーム");
  open("about");
  check($("#information-view").textContent.includes(w.SITE_CONTENT.medical.overview), "治療概要はLPと同じ原稿");
  check(d.querySelectorAll(".treatment-steps li").length === 4, "施術の流れ4段階");
  open("doctor");
  check($("#information-view").textContent.includes("上田 敬博") && $("#information-view img").getAttribute("src").includes("ueda-portrait"), "医師紹介と実写真");
  open("cases");
  check(d.querySelectorAll(".case-card").length === 6 && d.querySelectorAll(".case-pair img").length === 12, "比較写真6組・12点");
  for (const img of d.querySelectorAll(".case-pair img")) assert.ok(img.alt && fs.existsSync(path.resolve(root, "line", img.getAttribute("src"))));
  check(true, "症例画像の相対パス・代替テキスト");
  open("price");
  check($("#information-view").textContent.includes("30") && $("#information-view").textContent.includes("検討中") && $("#information-view").textContent.includes("アレルギー"), "仮料金・リスク・ダウンタイム");
  open("regions");
  check(d.querySelectorAll(".region-choice").length === 4 && $("#information-view").textContent.includes("開催日未定"), "希望地域と未確定会場");
  $('[data-region="osaka"]').click();
  check(!$("#registration-view").hidden && field("region").value === "osaka", "希望地域をフォームへ引継ぎ");
  submit();
  check(!$("#form-error").hidden && d.activeElement === field("fullName"), "空欄を拒否し最初の必須欄へフォーカス");
  $("#fill-demo").click();
  check(field("fullName").value === "デモ 太郎" && field("region").value === "osaka", "デモ入力で選択地域を維持");
  submit();
  check(!$("#form-error").hidden && $("#confirm-view").hidden, "確認チェックが必須");
  field("acknowledge").checked = true;
  set("fullName", "   "); submit();
  check(!$("#form-error").hidden, "空白だけの名前を拒否");
  set("fullName", "デモ 太郎"); set("contact", "invalid"); submit();
  check(!$("#form-error").hidden, "メール形式不正を拒否");
  set("contact", "demo@example.com");
  field("region").value = "other"; field("region").dispatchEvent(new w.Event("change"));
  check(!$("#other-region-field").hidden && field("otherRegion").required, "その他地域は追加入力が必須");
  submit(); check(!$("#form-error").hidden, "その他地域の未入力を拒否");
  set("otherRegion", "京都市"); submit();
  check(!$("#confirm-view").hidden && form.hidden && $("#confirm-values").textContent.includes("京都市"), "確認画面と入力値の引継ぎ");
  $("#edit-input").click();
  check(!form.hidden && field("otherRegion").value === "京都市" && !$("#confirm-values").children.length, "入力に戻ると内容を保持して確認表示を消去");
  field("contactMethod").value = "phone"; $('[name="contactMethod"][value="phone"]').dispatchEvent(new w.Event("change"));
  check(field("contact").type === "tel" && field("contact").value === "", "電話への切替時に入力方式と値を更新");
  set("contact", "123"); submit(); check(!$("#form-error").hidden, "短すぎる電話番号を拒否");
  set("contact", "090-0000-0000"); set("fullName", '<img src=x onerror="alert(1)">'); submit();
  check(!$("#confirm-view").hidden && !$("#confirm-values img") && $("#confirm-values").textContent.includes("<img"), "確認画面でHTMLを実行しない");
  $("#complete-demo").click();
  check(!$("#success-view").hidden && $("#success-region").textContent.includes("京都市"), "希望地域に応じた完了案内");
  check(field("fullName").value === "" && field("contact").value === "" && $("#confirm-values").textContent === "", "完了時に氏名・連絡先・確認データを消去");
  check($("#chat-events").textContent.includes("デモを完了") && !$("#chat-events").textContent.includes("090-0000"), "トークの完了案内に連絡先を出さない");
  const events = $("#chat-events").children.length; $("#complete-demo").click();
  check($("#chat-events").children.length === events, "完了の二重実行を防止");
  $("#success-chat").click();
  check($("#registration-view").hidden && $(".empty-view"), "PCでトークに戻るとメニュー選択案内");
  open("register");
  check(!form.hidden && field("fullName").value === "", "再登録は空の入力画面");
  $("#reset-demo").click();
  check($("#chat-events").children.length === 0 && field("region").value === "", "リセットで履歴と希望地域を消去");
  $("#menu-toggle").click();
  check($("#rich-menu").hidden && $("#menu-toggle").getAttribute("aria-expanded") === "false", "リッチメニューを閉じる");
  $("#menu-toggle").click(); check(!$("#rich-menu").hidden, "リッチメニューを開く");
  media.matches = true; mediaChange();
  check($(".detail-column").inert && !$(".chat-column").inert, "モバイル初期状態ではトークだけを操作可能");
  open("about");
  check(d.body.classList.contains("detail-open") && $(".chat-column").inert && !$(".detail-column").inert && d.activeElement === $("#information-view h2"), "モバイルで案内へ切替・見出しへフォーカス");
  d.dispatchEvent(new w.KeyboardEvent("keydown", { key: "Escape" }));
  check(!d.body.classList.contains("detail-open") && !$(".chat-column").inert && d.activeElement === $('#rich-menu [data-open="about"]'), "Escapeでトークに戻り元のボタンへフォーカス");
  open("regions"); $('[data-region="other"]').click(); $("#fill-demo").click();
  check(field("region").value === "other" && field("otherRegion").value === "京都市内", "その他地域のデモ入力も引継ぎ");
  $("#back-to-chat").click();
  check(!d.body.classList.contains("detail-open"), "戻るボタンでモバイルのトークへ");
  $("#reset-demo").click();
  check(field("fullName").value === "" && !$("#chat-events").children.length && !d.body.classList.contains("detail-open"), "モバイルでも完全リセット");
  $('.chat-header [data-open="account"]').click();
  check($("#information-view").textContent.includes("実際のLINEアカウントへの接続"), "デモの説明を開ける");
  check(connections.length === 0 && errors.length === 0, "送信API呼出し・DOM実行エラーなし");
  const js = fs.readFileSync(path.join(root, "assets/line-demo.js"), "utf8");
  check(!/\b(fetch|XMLHttpRequest|sendBeacon|localStorage|sessionStorage)\b|document\.cookie/.test(js), "送信・永続保存の実装なし");
  dom.window.close();
  console.log(`${count} LINE DOM checks passed. Real browser layout must be verified separately.`);
})().catch((err) => { console.error(err); process.exit(1); });
